### ISSUE TITLE
undefined method `to_hash_with_metadata' for nil:NilClass

### ISSUE THREAD

**Issue by arhue** [logstash-plugins/logstash-filter-multiline#36]
Logstash version: 6.6.1
Java version:
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

Error log:
```
[2019-03-18T07:50:44,820][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"main", "exception"=>"undefined method `to_hash_with_metadata' for nil:NilClass", "backtrace"=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-multiline-3.0.4/lib/logstash/filters/multiline.rb:273:in `block in merge'", "org/jruby/RubyArray.java:1734:in `each'", "org/jruby/RubyEnumerable.java:936:in `inject'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-multiline-3.0.4/lib/logstash/filters/multiline.rb:272:in `merge'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-multiline-3.0.4/lib/logstash/filters/multiline.rb:230:in `previous_filter!'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-multiline-3.0.4/lib/logstash/filters/multiline.rb:173:in `filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:143:in `do_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:162:in `block in multi_filter'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:159:in `multi_filter'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:115:in `multi_filter'", "(eval):1092:in `block in initialize'", "org/jruby/RubyArray.java:1734:in `each'", "(eval):1089:in `block in initialize'", "(eval):392:in `block in filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:358:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:337:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:304:in `block in start_workers'"], :thread=>"#<Thread:0x290c9bee@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:173 sleep>"}
[2019-03-18T07:50:44,927][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `to_hash_with_metadata' for nil:NilClass>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-multiline-3.0.4/lib/logstash/filters/multiline.rb:273:in `block in merge'", "org/jruby/RubyArray.java:1734:in `each'", "org/jruby/RubyEnumerable.java:936:in `inject'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-multiline-3.0.4/lib/logstash/filters/multiline.rb:272:in `merge'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-multiline-3.0.4/lib/logstash/filters/multiline.rb:230:in `previous_filter!'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-multiline-3.0.4/lib/logstash/filters/multiline.rb:173:in `filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:143:in `do_filter'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:162:in `block in multi_filter'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:159:in `multi_filter'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:115:in `multi_filter'", "(eval):1092:in `block in initialize'", "org/jruby/RubyArray.java:1734:in `each'", "(eval):1089:in `block in initialize'", "(eval):392:in `block in filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:358:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:337:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:304:in `block in start_workers'"]}
[2019-03-18T07:50:44,939][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
```

This results in logstash intermittently "flapping"(going down and coming back again). Would be happy to provide more info if needed.

**Comment by denzhel** [comment]
Have the same issue

**Comment by denzhel** [comment]
@arhue I think I found a solution. Not sure yet.

Elastic advises not to parse multiline with Logstash, rather with Filebeat.

I removed the multiline filters from Logstash and added the following to filebeat:
```
multiline.pattern: '^\['
multiline.negate: true
multiline.match: after 
```

Testing it as we speak with all the instances I had multiline configured on. Hopefully it will help, hope it helps you.

**Comment by hbbdgyb** [comment]
你就这样解决问题的吗？
@denzhel
